/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BBreadcrumb: typeof import('bootstrap-vue-next/components/BBreadcrumb')['BBreadcrumb']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BListGroupItem: typeof import('bootstrap-vue-next/components/BListGroup')['BListGroupItem']
    BreadCrumbs: typeof import('./src/components/BreadCrumbs.vue')['default']
    CategoryCard: typeof import('./src/components/CategoryCard.vue')['default']
    LanguageSelector: typeof import('./src/components/modals/LanguageSelector.vue')['default']
    LucideIcon: typeof import('./src/components/LucideIcon.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubcategoryCard: typeof import('./src/components/SubcategoryCard.vue')['default']
    WordCard: typeof import('./src/components/WordCard.vue')['default']
  }
}
